### ISSUE TITLE
Crash when searching symbols

### ISSUE THREAD

**Issue by Deleranax** [Dwight-Studio/JArmEmu#11]
Crash when searching in memory overview : '000000D0'. Adding a toast to alert the user?

```
[2024-09-19 11:22:10] [INFO] MemoryOverviewController: fr.dwightstudio.jarmemu.base.asm.exception.SyntaxASMException: Malformed math expression '000000D0' (For input string: "0000D0" under radix 8)
    at fr.dwightstudio.jarmemu.base.sim.entity.StateContainer.evalWithAll(StateContainer.java:231)
    at fr.dwightstudio.jarmemu.base.gui.controllers.MemoryOverviewController.lambda$initialize$7(MemoryOverviewController.java:170)
    at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Deleranax** [comment]
The exception was catched and logged, and it does not seam to induce any other problem
